config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects, only: [:index, :create, :destroy]

  get "github/:name" => "github_accounts#show"

  get "github/:github_owner/:github_name" => "reports#show_last_report",
      as: "show_last_report",
      constraints: { github_name: %r{[^\/]+} }
  get "github/:github_owner/:github_name/model-overview/" => "model_overview#show_last_report_model_overview",
      as: "show_last_report_model_overview",
      constraints: { github_name: %r{[^\/]+} }

  scope "/hooks", controller: :hooks do
    post :github_event
  end
end

app/models/project.rb
require "fileutils"
require "yaml"
require "shellwords"

class Project < ActiveRecord::Base
  belongs_to :added_by_user, class_name: "Woodlock::User", foreign_key: "added_by_user_id"
  belongs_to :owner_user, class_name: "Woodlock::User", foreign_key: "owner_user_id"
  belongs_to :github_account

  has_many :reports, dependent: :destroy

  before_create :associate_github_account
  before_destroy :remove_github_hook
  after_create :update_github_info

  serialize :github_collaborators, Array

  validates :github_url, uniqueness: true, format: { with: %r{https:\/\/github.com\/.*} }

  scope :public_repositories, -> { where(github_private: false) }
  scope :private_repositories, -> { where(github_private: true) }
  scope :with_analysis, -> { where(has_last_report_analyses: true) }
  scope :without_analysis, -> { where(has_last_report_analyses: false) }

  # Returns all projects matching a given query to the github_url, github_owner or github_name.
  def self.search(query)
    where("github_url like ?", "%#{query}%") ||
      where("github_owner like ?", "%#{query}%") ||
      where("github_name like ?", "%#{query}%")
  end

  # Returns all analysed projects within a search, where the user is a collaborator, ordered by github_name.
  def self.logged_in_search(search_params, current_user)
    with_analysis
      .search(search_params)
      .order("github_name")
      .reject do |project|
        project.github_private &&
          !current_user.github_repository_access?(project.repository_name)
      end
  end

  # Returns all public and analysed projects within a search, ordered by github_name.
  def self.logged_out_search(search_params)
    with_analysis
      .search(search_params)
      .public_repositories
      .order("github_name")
  end

  # Returns the latest n public and analysed projects, ordered by created_at.
  def self.latest_public_analysed(n)
    #with_analysis
    public_repositories
      .order("created_at DESC")
      .limit(n)
  end

  def repository_name
    "#{github_owner}/#{github_name}"
  end

  # Creates Github webhook for the project
  def create_github_hook
    owner_user = Woodlock::User.find_by(github_username: github_owner)
    return false unless owner_user

    client = Octokit::Client.new(access_token: owner_user.github_token)
    self.github_secret_token = SecureRandom.hex(20)
    save

    # TODO: Not working.
    create_hook_response =
      client.create_hook(
        repository_name,
        "web",
        { url: Rails.application.secrets.app_hooks_url, content_type: "json", secret: github_secret_token },
        { active: true, events: "push" }
      )

    self.github_webhook_id = create_hook_response["id"]
    save
    true
  end

  def remove_github_hook
    owner_user = Woodlock::User.find_by(github_username: github_owner)
    return unless owner_user && github_webhook_id.nil?

    client = Octokit::Client.new(access_token: owner_user.github_token)
    client.remove_hook(repository_name, github_webhook_id)
    self.github_webhook_id = nil
    save
  end

  def update_owner_and_name_from_url
    extract_info_from_url
    save
  end

  # Assigns github_name and github_owner attributes from github_url attribute.
  def extract_info_from_url
    splitted_url = github_url.delete(" ").split("/")
    self.github_name  = splitted_url[-1]
    self.github_owner = splitted_url[-2]
  end

  # Creates a new client connection to Github and updates project related github attributes.
  def update_github_info
    update_owner_and_name_from_url

    client = Octokit::Client.new(access_token: added_by_user.github_token)
    github_repository =
      client.repository?(repository_name) ? client.repository(repository_name) : nil
    return unless github_repository

    self.github_forks = github_repository.forks
    self.github_watchers = github_repository.watchers
    self.github_size = github_repository.size
    self.github_private = github_repository.private
    self.github_homepage = github_repository.homepage
    self.github_description = github_repository.description
    self.github_fork = github_repository.fork
    self.github_has_wiki = github_repository.has_wiki
    self.github_has_issues = github_repository.has_issues
    self.github_open_issues = github_repository.open_issues
    self.github_pushed_at = github_repository.pushed_at
    self.github_created_at = github_repository.created_at
    self.github_collaborators = client.collaborators(repository_name).map(&:to_hash) if self.github_private

    self.save
  end

  def last_percents(n)
    percents = percents_array(n)
    percents.present? ? percents.to_json : false
  end

  private

  def associate_github_account
    existing_github_account = GithubAccount.find_by(name: github_owner)
    self.github_account =
      existing_github_account || GithubAccount.create!(name: github_owner)
  end

  def percents_array(n)
    reports_with_code_coverage_analysis_percent =
      Report.includes(:code_coverage_analysis)
      .where(project_id: id)
      .where.not(code_coverage_analyses: { percent: nil })
      .order(created_at: :desc)
      .limit(n)

    reports_with_code_coverage_analysis_percent.map do |report|
      {
        "info" => {
          "commit_hash": report.commit_hash,
          "created_at": report.created_at.strftime("%d-%b-%y"),
          "percent": report.code_coverage_analysis.percent
        }
      }
    end.compact
  end
end

app/controllers/projects_controller.rb
require "securerandom"

class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  before_action :set_new_project, only: [:index, :new]
  before_action :set_index_instance_variables, only: :index

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_project

  def index
    return unless params[:search]

    @searched_projects = logged_in_out_project_search

    if exact_url_search?(@searched_projects)
      project = @searched_projects.first
      redirect_to github_project_owner_name_url(project.github_owner, project.github_name), notice: "Here's the project you searched for."
    elsif @searched_projects.blank?
      flash[:warning] = "No results found."
    end
  end

  def create
    create_project = create_project_with_default_attributes

    if create_project.current_user_repository_access?
      if create_project.save_project
        if create_project.owner_user_in_db?
          create_project.project.create_github_hook
          redirect_to projects_url, notice: "Project was successfully submitted."
        else
          redirect_to projects_url, notice: "Project was successfully submitted. Waiting for owner to login."
        end
      else
        render :new
      end
    else
      redirect_to projects_url, alert: "We're sorry. Either the project doesn't exist or you don't have permission to add it."
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: "Project was successfully destroyed."
  end

  private

  def create_project_with_default_attributes
    create_project = CreateProject.new(project_params: project_params, current_user: current_user)
    # returns create_project object
    create_project.assign_default_attributes
  end

  def assign_project_when_valid_params
    return unless params[:github_owner] && params[:github_name]

    @project =
      Project.find_by(github_owner: params[:github_owner], github_name: params[:github_name])
  end

  def logged_in_out_project_search
    if current_user
      Project.logged_in_search(params[:search], current_user)
    else
      Project.logged_out_search(params[:search])
    end
  end

  def set_index_instance_variables
    @searched_projects = nil
    @existing_projects = []
    @missing_projects = []

    user_repositories = current_user ? current_user.github_repositories : false

    if !user_repositories
      @latest_public_analysed_projects = Project.latest_public_analysed(100)
      return
    end

    repositories_info =
      user_repositories.map do |repository|
        {
          repository_name: repository.owner.login + "/" + repository.name,
          github_name: repository.name,
          github_owner: repository.owner.login,
          github_private: repository.private,
          svn_url: repository.svn_url
        }
      end

    @existing_projects =
      Project.where(
        github_name: repositories_info.map { |info| info[:github_name] },
        github_owner: repositories_info.map { |info| info[:github_owner] }
      )

    @latest_public_analysed_projects = Project.latest_public_analysed(@existing_projects.count.clamp(5, 100))

    existing_projects_repository_names = @existing_projects.map { |p| p.repository_name }

    @missing_projects =
      repositories_info.reject do |repo|
        existing_projects_repository_names.include?(repo[:repository_name])
      end
  end

  def set_new_project
    @project = Project.new
  end

  def exact_url_search?(searched_projects)
    searched_projects &&
      searched_projects.count == 1 &&
      params[:search] == searched_projects.first.github_url
  end

  def invalid_project
    logger.error "Attempt to access invalid projects #{params[:id]}"
    redirect_to projects_url, alert: "Invalid project. RecordNotFound"
  end

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:github_url, :github_owner, :github_name, :github_forks, :github_watchers, :github_size, :github_private, :github_homepage, :github_description, :github_fork, :github_has_wiki, :github_has_issues, :github_open_issues, :github_pushed_at, :github_created_at, :github_collaborators, :has_last_report_analyses)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def humanized_description(project)
    rbp_score = project.reports.last.rails_best_practices_analysis.nbp_report_to_hash["rbp_score"].to_i
    watchers_and_forks_count = project.github_watchers + project.github_forks

    if project.github_private
      private_project_message(project)
    elsif rbp_score > 2 &&
          watchers_and_forks_count < rbp_score * 30 &&
          project.github_created_at > 1.year.ago
      recent_and_good_message(project)
    elsif rbp_score > 2 && watchers_and_forks_count > rbp_score * 100
      good_forst_message(project)
    elsif rbp_score < 3 && project.pushed_at < 1.year.ago
      old_project_message(project)
    else
      normal_report_message(project)
    end
  end

  private

  def private_project_message(project)
    "The project #{project.github_name} is private. Description not available yet."
  end

  def recent_and_good_message(project)
    "#{project.github_name.capitalize} has <strong>#{project.github_watchers} watchers</strong> and <strong>#{project.github_forks} forks</strong> on GitHub. These are not big numbers for a project with a <strong>score of #{project.reports.last.rails_best_practices_analysis.score}</strong>, however the GitHub repository was only created #{time_ago_in_words project.github_created_at} ago. The last update happened #{time_ago_in_words (Time.zone.today - (project.updated_at.to_date - project.github_pushed_at).to_i.days)} before this analisys."
  end

  def old_project_message(project)
    "#{project.github_name.capitalize} has <strong>#{project.github_watchers} watchers</strong> and <strong>#{project.github_forks} forks</strong>. The GitHub repository was created #{time_ago_in_words project.github_created_at} ago, but it had no activity for #{time_ago_in_words project.github_pushed_at} ago. This might explain the low score."
  end

  def good_forks_message(project)
    "#{project.github_name.capitalize} has <strong>#{project.github_watchers} watchers</strong> and <strong>#{project.github_forks}</strong> forks on GitHub. This numbers match the hight level quality of the project.github_ The repository was created #{time_ago_in_words project.github_created_at} ago and the last update happened #{time_ago_in_words (Time.zone.today - (project.updated_at.to_date - project.github_pushed_at).to_i.days)} before this analisys."
  end

  def normal_report_message(project)
    "The repository was created #{time_ago_in_words project.github_created_at} ago, it has <strong>#{project.github_watchers} watchers</strong> and <strong>#{project.github_forks} forks</strong> on GitHub. The last updated happened #{time_ago_in_words project.github_pushed_at} ago."
  end
end

app/views/projects/_add_project_on_blank_search.html.erb
<% if current_user && params[:search] && @searched_projects.blank? %>
<div class="row">
  <div class="col s12">

    <%= form_for @project do |f| %>
      <div class="field form-group">
        <%= f.text_field :github_url, placeholder: 'Insert new Github URL if you want to submit a new project.', class: 'form-control' %>
      </div>
      <div class="action">
        <%= f.submit 'Add new project', class: 'btn btn-default' %>
      </div>
    <% end %>

  </div>
  </div>
<% end %>

app/views/projects/_form.html.erb
<div class="well">
  <%= form_for project do |f| %>
    <% if project.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h2><%= pluralize(project.errors.count, "error") %> <%= t('error_saving') %>:</h2>
        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :github_url, "GitHub URL" %>
      <%= f.text_field :github_url, class: 'form-control' %>
      <span class="help-block">Should be the url to rails project in GitHub.</span>
    </div>

    <div class="field form-group">
      <%= f.check_box :analysed %>
      <%= label(:project, :analysed, 'Update Repository and Generate New Report') %>
    </div>

    <div class="action">
     <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/projects/_project_list.html.erb
<div class="row">
  <% if existing_projects.present? %>
  <div class="col s12 l6">
    <div class="collection with-header">
      <div class="collection-header"><h4>Your Repositories</h4></div>
      <% existing_projects.each do |project| %>
      <%= link_to show_last_report_path(project.github_owner, project.github_name), class: "collection-item" do %>

      <% unless project.has_last_report_analyses %>
      <span class="new badge blue-grey darken-2" data-badge-caption="WAITING TO BE ANALYSE"></span>
      <% end %>
      <span class="blue-grey-text text-darken-2">
        <i class="material-icons left"><%= project.github_private ? 'lock' : 'public' %></i>
        <%= project.github_owner %>/<%= project.github_name %>
      </span>

      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>

  <% if @latest_public_analysed_projects.present? %>
  <div class="col s12 <%='l6' if existing_projects.present? %>">
    <div class="collection with-header">
      <div class="collection-header"><h4>Latest Public Repositories</h4></div>
      <% @latest_public_analysed_projects.each do |project| %>
      <%= link_to show_last_report_path(project.github_owner, project.github_name), class: "collection-item" do %>

      <% unless project.has_last_report_analyses %>
      <span class="new badge blue-grey darken-2" data-badge-caption="WAITING TO BE ANALYSE"></span>
      <% end %>
      <span class="blue-grey-text text-darken-2">
        <i class="material-icons left"><%= project.github_private ? 'lock' : 'public' %></i>
        <%= project.github_owner %>/<%= project.github_name %>
      </span>

      <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

<% if missing_projects.present? %>
<div class="row">
  <div class="col s12">
    <ul class="collection with-header">
      <li class="collection-header"><h4>Analyse Your Github Repositories</h4></li>
      <% missing_projects.each do |project| %>
      <li class="collection-item">

        <div>
          <span class="blue-grey-text text-darken-2">
            <i class="material-icons left"><%= project[:github_private] ? 'lock' : 'public' %></i>
            <%= project[:github_owner] %>/<%= project[:github_name] %>
          </span>
          <%= form_for @project, html: { class: "secondary-content" } do |f| %>
          <%= f.hidden_field :github_url, value: project[:svn_url] %>
          <%= f.submit "Add Repository", class: "btn btn-small" %>
          <% end %>
        </div>

      </li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/projects/_rails_best_practices_info.html.erb
<div class="page-header">
  <h1>NBP Report <small>occurrences of best practices infractions</small></h1>
</div>

<p>A total of <%= @project.nbp_report_to_mx_hash[:total_files_analyzed] %> were analyzed. <%= @project.nbp_report_to_mx_hash[:nbps] %></p>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>Best Practice Description</th>
    <th>Errors found</th>
    <th>NBP Score</th>
  </tr>
  <% 34.times do |i| ; m = project.nbp_report_to_mx_hash[i+1] %>
    <tr class="<%= 'red' if m[:r].to_i > 499 %>">
      <td><%= m[:l].gsub("_"," ").capitalize %></td>
      <td><%= m[:o] %> errors ( <%= m[:n] %> files analyzed )</td>
      <td><%= m[:r] %></td>
    </tr>
  <% end %>
</table>

app/views/projects/_search_project_form.html.erb
<nav>
  <div class="nav-wrapper">
    <%= form_tag(projects_path, method: 'get', role: 'form') do %>
    <div class="input-field">
      <%= text_field_tag :search, params[:search], placeholder: 'Project url, owner or name', required: true, type: 'search', class: 'autocomplete' %>
      <label class="label-icon" for="search"><i class="material-icons">search</i></label>
    </div>
    <% end %>
  </div>
</nav>

app/views/projects/_searched_projects.html.erb
<% if searched_projects.present? %>

<div class="row">
  <div class="col s12">

    <div class="collection with-header">
      <div class="collection-header"><h4>We've <span class='bigger-text'>found <%= pluralize(searched_projects.count, 'match') %></span> for your search.</h4></div>
      <% searched_projects.each do |project| %>
      <%= link_to show_last_report_path(project.github_owner, project.github_name), class: "collection-item" do %>

      <% unless project.has_last_report_analyses %>
      <span class="new badge blue-grey darken-2" data-badge-caption="WAITING TO BE ANALYSE"></span>
      <% end %>
      <span class="blue-grey-text text-darken-2">
        <i class="material-icons"><%= project.github_private ? 'lock' : 'public' %></i>
        <%= project.github_owner %>/<%= project.github_name %>
      </span>

      <% end %>
      <% end %>
    </div>

  </div>
</div>
<% end %>

app/views/projects/index.html.erb
<div class="row">
  <div class="col s12">
    <%= render "search_project_form" %>
  </div>
</div>

<%= render "searched_projects", searched_projects: @searched_projects %>
<%= render "add_project_on_blank_search", searched_projects: @searched_projects, project: @project %>
<%= render "project_list", existing_projects: @existing_projects, missing_projects: @missing_projects %>