config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects, only: [:index, :create, :destroy]

  get "github/:name" => "github_accounts#show"

  get "github/:github_owner/:github_name" => "reports#show_last_report",
      as: "show_last_report",
      constraints: { github_name: %r{[^\/]+} }
  get "github/:github_owner/:github_name/model-overview/" => "model_overview#show_last_report_model_overview",
      as: "show_last_report_model_overview",
      constraints: { github_name: %r{[^\/]+} }

  scope "/hooks", controller: :hooks do
    post :github_event
  end
end

app/models/report.rb
require "yaml"

class Report < ActiveRecord::Base
  belongs_to :project
  belongs_to :rails_best_practices_analysis, class_name: "Analyses::RailsBestPracticesAnalysis", dependent: :destroy
  belongs_to :model_diagram_analysis, class_name: "Analyses::ModelDiagramAnalysis", dependent: :destroy
  belongs_to :code_coverage_analysis, class_name: "Analyses::CodeCoverageAnalysis", dependent: :destroy

  validates :commit_hash, presence: true
  validates :branch, presence: true
  validates :project, presence: true

  delegate :github_name, to: :project, prefix: true
  delegate :github_owner, to: :project, prefix: true

  # Returns true if rails_app_path attribute is present.
  def rails_app_present?
    rails_app_path? ? true : false
  end

  # Returns true if gc_config attribute is present and has "rvm" and "before_script" keys.
  def gc_config_valid?
    gc_config.present? && gc_config["rvm"].present? && gc_config["before_script"].present?
  end

  # Returns gc_config attribute in YAML
  def gc_config_to_yml
    YAML.load(gc_config)
  end

  def rbp_description
    rails_best_practices_analysis ? rails_best_practices_analysis.nbp_report_to_hash["description"] : false
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ProjectAccessBlocker

  before_action :set_last_report_variables, only: :show_last_report

  def show_last_report
    if @project
      if block_project_access?(@project, current_user)
        redirect_to projects_url, alert: "You don't have access to this project."
      end
      @number_of_percents = 30
    else
      redirect_to projects_url, alert: "Invalid project."
    end
  end

  private

  def set_last_report_variables
    return unless params[:github_owner] && params[:github_name]
    @project =
      Project.where(github_owner: params[:github_owner], github_name: params[:github_name]).first
    @last_report = @project.reports.last || nil
  end
end

app/views/reports/_last_report.html.erb
<div>
  <h1 class="display-inline-block" style="font-size: <%= 70 - project.github_name.length || 0 %>px;">
    <% if project.github_private %>
      <i class="fa fa-lock"></i>
    <% end %>
    <%= project.github_name %>
  </h1>
  <span class="float-right"><%= link_to project.github_name, project.github_url %> by <%= @project.github_owner %></span>
</div>

<%= content_tag(:p, last_report.rbp_description.capitalize + (desc[-1] == "." ? "" : ".")) if last_report.rbp_description %>

<% if last_report.rails_best_practices_analysis %>
  <div class="well">
    <p><%= humanized_description(project).html_safe %></p>
  </div>
<% end %>

<%= link_to '<i class="material-icons left">arrow_back</i>Go Back'.html_safe, projects_path, class: 'btn' %>
<%= link_to '<i class="material-icons left">grain</i>Model overview'.html_safe, show_last_report_model_overview_path(project.github_owner, project.github_name), class: 'btn' %>
<%= link_to '<i class="material-icons left">code</i>Source Code'.html_safe, project.github_url, class: 'btn', target: '_blank' %>
<hr>

<% if last_report && last_report.model_diagram_analysis && last_report.model_diagram_analysis.json_data? %>
  <% model_diagram_json = last_report.model_diagram_analysis.json_data %>
  <script>
    var model_diagram_json = <%= raw model_diagram_json %>;
    var git_bash_path = "<%= @project.github_url %>";
  </script>

  <h4>Model diagram</h4>

  <input type="button" value="Load" id="loadBtn" />
  <input type="button" value="Save" id="saveBtn" />
  <input type="button" value="Release" id="release" />

  <div id="svg-model-diagram">
  </div>

  <div class="svg-model-diagram-info well">
    <div id="model-diagram-info">
      <p class="model-info-title text-muted">Model information</p>
    </div>
  </div>
  <hr>
<% else %>
  <p class="text-muted">Diagram not available</p>
  <hr>
<% end %>

<% if project.last_percents(@number_of_percents) %>
  <script>
var code_coverage_json = <%= raw project.last_percents(@number_of_percents) %>;
  </script>

  <div class="row">
    <div class="col-md-9">
      <h4>Code coverage timeline</h4>
    </div>
    <div class="col-md-3">
      <p class="text-muted margin-top-10">Last percent: <%= last_report.code_coverage_analysis.percent %>%</p>
    </div>
  </div>
  <div id="svg-code-coverage-diagram">
  </div>
<% else %>
  <p class="text-muted">Code coverage diagram not available</p>
<% end %>

<% if last_report.rails_best_practices_analysis %>
  <div class="row">
    <div class="col-md-12">
      <span class="rbp-score">Rails best practices score: </span>
      <span class="rbp-score-value"><%= last_report.rails_best_practices_analysis.final_score  %> out of 5</span>
    </div>
  </div>
<% end %>

app/views/reports/show_last_report.html.erb
<% if @project.has_last_report_analyses && @last_report %>
  <%= render "last_report", project: @project, last_report: @last_report %>
<% else %>
  <div class="alert alert-warning">
    <span><%= link_to @project.github_name, @project.github_url %> by <%= @project.github_owner %></span>
    <p>This project is waiting for analysis</p>
  </div>
  <%= link_to '<i class="fa fa-arrow-left"></i> Go Back'.html_safe, projects_path, class: "btn btn-primary btn-large" %>
<% end %>